### PR TITLE
Misc. improvements

### PR DESCRIPTION
**Pull request by Pyrohh**
Some of these changes might be too opinionated, so critique away.

### CODE REVIEW

**Comment by fmoralesc** [comment]
LGTM. I'm not fanatical about tabs vs spaces; on the contrary, I'm super sloppy. Can you add some modelines so the formatting is consistent next time I touch the files? ;) The changes re: `<ENTER>` seem fine to me.

**Comment by Pyrohh** [comment]
I'll add in modelines next time :)

Speaking of formatting, I saw that`tutor.vim` sets `textwidth`, which I'm unsure about. It seems better to just use modelines, especially since other tutorials might use different values (78 is very common).

**Comment by fmoralesc** [comment]
I thought about `textwidth` and it seems like it's better to remove that (which I just did). Anyway, in some cases (for example, with links), textwidth can be a PITA. It should adjust itself depending on the visible length of the lines, and that seems way too precious to implement, at least for now.

Thanks for the improvements, btw.

**Comment by Pyrohh** [comment]
Sure thing.

**Pull request merged**
