### PR TITLE
Don't modify 'cursorline', 'statusline'

### LINKED ISSUE #15: Don't change 'statusline' / 'cursorline'
It's intrusive IMO, and I don't see its purpose currently as `tutor#InfoText` looks unused.

Regarding cursorline, do we really need it? I might be missing something there.

### PR DESCRIPTION
**Pull request by Pyrohh**
closes #15

### CODE REVIEW

**Comment by Pyrohh** [comment]
Thanks man!

**Comment by Pyrohh** [comment]
yeah sure :sunglasses:

**Comment by fmoralesc** [comment]
That is some smooth reviewing! Kudos to the maintainers for keeping things cool.

**Comment by Pyrohh** [comment]
I try...

**Comment by fmoralesc** [comment]
clap

**Comment by Pyrohh** [comment]
image

**Pull request merged**
